on:
  push:
    branches-ignore:
    - "ga-ignore-*"
  pull_request:
    branches-ignore:
    - "ga-ignore-*"

jobs:
  My_first_action:
    name: "Greetings"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: echo_command
        run: |
        echo "Hello, world!"
        mkdir -p Polp/ && cp -R dist Plop/