name: My first action

on:
  push:
    branches-ignore:
    - "ga-ignore-*"
  pull_request:
    branches-ignore:
    - "ga-ignore-*"

jobs:
    Greetings:
    name: "Setup job"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: echo
        run: echo "Hello"