name : Action
on:
  push:
    branches :
      - "master"
      - "main"

jobs:
  Hello_Python:
    name: "Hello_python"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: exec_cmd
      run: |
        cd app/python
        python3 hello.py