on:
  push:
    branches-ignore:
    - "ga-ignore-*"
  pull_request:
    branches-ignore:
    - "ga-ignore-*"

jobs:
  My_first_action:
    name: "Greetings"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: echo "Hello, world!"
        run: echo "Hello, world!"