name: Compil

on:
  push:
  pull_request:
    branches-ignore:
    - "ga-ignore-*"

jobs:
  compil:
    name: "check if the make compil"
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    if: "!contains(github.event.head_commit.message, 'skio ci')"
    steps:
      - uses: actions/checkout@v2
      - id: check_if_compil
        run: cd app/c && make
  test:
    needs: [compil]
    name: "make test"
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest

    steps:
      - uses: actions/checkout@v2
      - id: make_test
        run: cd app/c && make test_run