name: Compil

on:
  push:
  pull_request:
    branches-ignore:
    - "ga-ignore-*"

jobs:
  check_if_compil:
    name: "check if the make compil"
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    if: "!contains(github.event.head_commit.message, 'skio ci')"
    steps:
      - uses: actions/checkout@v2
      - id: check_if_compil
        run: cd app/c make
        timeout-minutes: 2
      - run: make clean