name: Multi_OS

on:
  push:
    branches :
      - "master"
      - "main"

jobs:
  My_first_action:
    name: "Greetings"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: echo_command
      if: "!contains(github.event.head_commit.message, 'ci skip')"  
        run: |
          echo "test"