name: Multi_OS

on:
  push:
    branches :
      - "master"
      - "main"

jobs:
  My_first_action:
    name: "WinduntuOS"
    strategy:
      matrix:
        version: [ubuntu-latest, windows-latest, macOS-latests]
    if: "!contains(github.event.head_commit.message, 'skio ci')"
    steps:
      - uses: actions/checkout@v2
      - id: echo_command
        run: |
          echo "Hello from" ${{ matrix.version }}