name: Multi_OS

on:
  push:
    branches :
      - "master"
      - "main"
    tags-ignore:
    - "[skip ci]"

jobs:
  My_first_action:
    name: "Greetings"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: echo_command
        run: |
          echo "test"