name: Multi_OS

on:
  push:
    branches :
      - "master"
      - "main"

jobs:
  My_first_action:
    name: "WinduntuOS"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        version: [14]
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skio ci')"
    steps:
      - uses: actions/checkout@v2
      - id: echo_command
        run: |
          echo "Hello from ${{ matrix.os }}"