name: Multi_OS

on:
  push:
    branches :
      - "master"
      - "main"

jobs:
  if: "!contains(github.event.head_commit.message, 'ci skip')"
    My_first_action:
      name: "Greetings"
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - id: echo_command
          run: |
            echo "test"